spring:
  # driver-class-name: com.mysql.cj.jdbc.Driver
  # url : jdbc:mysql://localhost:3306/reservation-app?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
  # username: rhtjdxo
  # password: dawoon1106
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa :
    show-sql: true
    hibernate :
      ddl-auto : create
      format_sql : true
