spring:
  # driver-class-name: com.mysql.cj.jdbc.Driver
  # url : jdbc:mysql://localhost:3306/reservation-app?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
  # username: rhtjdxo
  # password: dawoon1106
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa :
    show-sql: true
    hibernate :
      ddl-auto : create
      format_sql : true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
springdoc:
  show-login-endpoint: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui-custom.html
    enabled: true
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  cache:
    disabled: true
  model-and-view-allowed: true

